before:
  hooks:
    - go mod tidy

builds:
  - id: concurrenthash
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: concurrenthash
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js
    goarch:
      - amd64
      - arm64

archives:
  - id: dist
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  # note that this is an array of nfpm configs
  - # ID of the nfpm config, must be unique.
    #
    # Default: 'default'
    id: concurrenthash

    # Name of the package.
    # Default: ProjectName
    package_name: concurrenthash

    # You can change the file name of the package.
    #
    # Default: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    # Templates: allowed
    #file_name_template: "{{ .ConventionalFileName }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults empty, which means no filtering.
    builds:
      - concurrenthash

    # Your app's vendor.
    vendor: Kevin Mulvey

    # Your app's homepage.
    homepage: https://github.com/kmulvey/concurrenthash

    # Your app's maintainer (probably you).
    maintainer: Drummer <drum-roll@example.com>

    # Your app's description.
    description: |-
      Threaded hashing for large files.

    # Your app's license.
    license: MIT

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Since: v1.11
      - archlinux # Since: v1.13

    # Packages your package depends on. (overridable)
    # dependencies:
    #   - git
    #   - zsh

    # Packages it provides. (overridable)
    #
    # Since: v1.11
    provides:
      - concurrenthash

    # Path that the binaries should be installed.
    # Default: '/usr/bin'
    bindir: /usr/bin

    # Version Epoch.
    # Default: extracted from `version` if it is semver compatible
    epoch: 2

    # Version Prerelease.
    # Default: extracted from `version` if it is semver compatible
    prerelease: beta1

    # Version Metadata (previously deb.metadata).
    # Setting metadata might interfere with version comparisons depending on the
    # packager.
    #
    # Default: extracted from `version` if it is semver compatible
    version_metadata: git

    # Version Release.
    release: 1

    # Section.
    section: default

    # Priority.
    priority: extra

    # Changelog YAML file, see: https://github.com/goreleaser/chglog
    #
    # You can use goreleaser/chglog to create the changelog for your project,
    # pass that changelog yaml file to GoReleaser,
    # and it should in turn setup it accordingly for the given available
    # formats (deb and rpm at the moment).
    #
    # Experimental.
    # Since: v1.11
    # changelog: ./foo.yml

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    # contents:
    #   # Basic file that applies to all packagers
    #   - src: ./dist/concurrenthash_linux_amd64_v1/concurrenthash
    #     dst: /usr/bin/concurrenthash

    # Custom configuration applied only to the RPM packager.
    rpm:
      group: root
      compression: lzma
      # The package is signed if a key_file is set
      #signature:
      # PGP secret key file path (can also be ASCII-armored).
      # The passphrase is taken from the environment variable
      # `$NFPM_ID_RPM_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
      # where ID is the id of the current nfpm config.
      # The id will be transformed to uppercase.
      # E.g. If your nfpm id is 'default' then the rpm-specific passphrase
      # should be set as `$NFPM_DEFAULT_RPM_PASSPHRASE`
      #
      # Templates: allowed
      #key_file: "/home/kmulvey/keys/sec.gpg"
